### ISSUE TITLE
Supported Kubernetes Version

### ISSUE THREAD

**Issue by irvifa** [stefanprodan/kube-tools#11]
First, thank you for this, it does help :)

I'd like to know which kubectl version supported by this image, as we know there's might be different api representation for each releases. Especially if specific API is promoted from Alpha to Beta.

**Comment by stefanprodan** [comment]
You can set whatever version you want with:

```yaml
      - uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
```

As for the kubectl that comes with the image, see the [release page](https://github.com/stefanprodan/kube-tools/releases)
