### ISSUE TITLE
how to inject kube config?

### ISSUE THREAD

**Issue by debianmaster** [stefanprodan/kube-tools#12]
when using this action how to inject kubeconfig?

**Comment by riker09** [comment]
I solved this by echoing the content of my `${{ secret.KUBECONFIG }}` into the standard path of the Kubernetes config file, `$HOME/.kube/config` like this:

```yaml
name: Deploy

on:
  deployment:

env:
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir -p .kube
        echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG

    - uses: stefanprodan/kube-tools@v1
      with:
        helmv3: 3.2.1
        command: |
          kubectl create namespace --ignore ${{ github.event.deployment.payload.namespace }} || true

```
